dist: xenial

language: python
python:
  - '3.6'
  - '3.7'

sudo: true

services:
  - mysql

install:
  - cd $HOME
  - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-8.0.16.tar.gz
  - tar zxvf mysql-connector-python-8.0.16.tar.gz
  - cd mysql-connector-python-8.0.16
  - python3 setup.py install
  - pip3 install pystratum

before_script:
  - mysql --version
  - mysql -u root -e "create database if not exists test;"
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"

script:
  - cd $TRAVIS_BUILD_DIR
  - cat pystratum_test/ddl/create_tables.sql | mysql -utest -ptest test
  - python3 -m unittest pystratum_test/*.py
